// GENERATED by @gel/generate v0.6.2

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
export type $ChallengeλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "expires_at": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, false>;
  "nonce": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
}>;
type $Challenge = $.ObjectType<"default::Challenge", $ChallengeλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "default::Challenge">;
const $Challenge = $.makeType<$Challenge>(_.spec, "68bd4078-26b8-11f0-a0eb-e34b0fae9dca", _.syntax.literal);

const Challenge: $.$expr_PathNode<$.TypeSet<$Challenge, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Challenge, $.Cardinality.Many), null);

export type $UserλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "wallet": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
}>;
type $User = $.ObjectType<"default::User", $UserλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "default::User">;
const $User = $.makeType<$User>(_.spec, "68bc4e16-26b8-11f0-a547-bd53ad0a3b08", _.syntax.literal);

const User: $.$expr_PathNode<$.TypeSet<$User, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($User, $.Cardinality.Many), null);



export { $Challenge, Challenge, $User, User };

type __defaultExports = {
  "Challenge": typeof Challenge;
  "User": typeof User
};
const __defaultExports: __defaultExports = {
  "Challenge": Challenge,
  "User": User
};
export default __defaultExports;
